app = "cash-api"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builder = "node"

[env]
  PORT = "3000"

[[services]]
  protocol = "tcp"
  internal_port = 3000

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]